# -*- coding: utf-8 -*-
# v2：把重疊/易混淆的工具重新定義得更精確，並附上每個工具的中文說明+一個範例
TOOL_SPECS = {
    "open_app": "啟動一個應用程式視窗（例如瀏覽器、記事本、設定、控制台、工作管理員、命令提示字元、VS Code），純粹「開啟」動作，不含後續操作",
    "close_window": "關閉目前這一個視窗",
    "window_op": "視窗管理：切換視窗、最小化、全螢幕、關閉全部正在跑的程式",
    "set_volume": "調整系統音量大小或設成特定百分比（不含播放/暫停音樂本身）",
    "media_control": "音樂/媒體的播放控制：播放、暫停、上下一首、靜音音樂",
    "get_datetime": "查詢現在時間、星期幾、日期",
    "get_weather": "查詢天氣狀況或天氣預報",
    "get_exchange_rate": "查詢貨幣匯率",
    "adjust_brightness": "調整螢幕亮度",
    "take_screenshot": "螢幕截圖",
    "clipboard_op": "複製、貼上文字或內容到剪貼簿",
    "file_op": "本機檔案操作：搜尋、刪除、重新命名、建立資料夾、另存成PDF、建立文字檔（不涉及雲端上傳下載）",
    "cloud_file_op": "雲端檔案操作：上傳、下載、分享檔案給別人（明確牽涉雲端或他人）",
    "power_op": "整台電腦的電源狀態：重新啟動、關機、休眠（不是單一裝置如Wi-Fi/藍牙的開關）",
    "network_toggle": "網路相關硬體開關與狀態：Wi-Fi、藍牙的開/關、查看網路連線狀態",
    "calendar_op": "行事曆：新增會議、排定事件",
    "reminder_op": "提醒/待辦事項：設定提醒我做某事、記錄待辦清單（不是鬧鐘時間）",
    "alarm_op": "鬧鐘：設定、關閉、延後鬧鐘時間",
    "print_or_scan": "列印或掃描實體文件",
    "photo_edit": "照片編輯：旋轉、裁切、放大縮小、編輯照片",
    "text_input_op": "把使用者說的一段話直接輸入/打字到目前的欄位或文件",
    "text_to_speech_op": "把文字轉換成語音朗讀出來",
    "speech_to_text_op": "把語音錄音轉換成文字",
    "translate": "把一句話翻譯成另一種語言",
    "calculator": "數學計算（含開啟小算盤來算數學）",
    "email_op": "電子郵件：收信、寄信、回覆、刪除郵件",
    "video_call_op": "啟動視訊會議/視訊通話軟體",
    "record_screen": "開始或停止螢幕錄影（不含錄影檔案本身的存檔動作，那是file_op）",
    "system_maintenance": "系統健康維護：檢查更新、安裝更新、掃描病毒、清理垃圾檔案、查看硬碟空間",
    "task_scheduler_op": "工作排程器：新增/管理定期自動執行的排程任務（跟工作管理員 open_app 不同，是「排程」不是「查看正在跑的程式」）",
    "startup_program_op": "開機自動啟動程式的新增或移除設定",
    "driver_op": "顯示卡/裝置驅動程式的查詢版本或更新（不是裝置管理員本身的開啟，那是open_app）",
    "dev_tool_op": "執行/編譯程式碼、跑 Script（PowerShell/Python），純粹「執行」動作本身",
    "git_op": "Git 版本控制操作：clone、commit、push、log、切換分支、建分支、合併分支、解決衝突",
    "summarize_doc": "把一份文件整理成重點摘要",
}
TOOLS = list(TOOL_SPECS.keys())

FEWSHOT = [
    ("打開瀏覽器", "open_app"),
    ("打開工作管理員", "open_app"),
    ("打開任務排程器", "open_app"),
    ("新增一個排程任務", "task_scheduler_op"),
    ("把藍牙打開", "network_toggle"),
    ("重新啟動電腦", "power_op"),
    ("打開裝置管理員", "open_app"),
    ("檢查顯示卡的驅動程式版本", "driver_op"),
    ("幫我搜尋這台電腦裡的文件", "file_op"),
    ("把這個檔案上傳到雲端", "cloud_file_op"),
    ("清理電腦裡的垃圾檔案", "system_maintenance"),
    ("提交這次的程式修改", "git_op"),
    ("執行這個 Python 腳本", "dev_tool_op"),
]

LABELS = {
1:"open_app",2:"open_app",3:"close_window",4:"set_volume",5:"set_volume",
6:"get_datetime",7:"get_datetime",8:"get_weather",9:"open_app",10:"file_op",
11:"adjust_brightness",12:"adjust_brightness",13:"take_screenshot",14:"clipboard_op",15:"clipboard_op",
16:"file_op",17:"file_op",18:"file_op",19:"window_op",20:"window_op",
21:"window_op",22:"window_op",23:"power_op",24:"power_op",25:"power_op",
26:"open_app",27:"open_app",28:"open_app",29:"network_toggle",30:"network_toggle",
31:"network_toggle",32:"network_toggle",33:"network_toggle",34:"media_control",35:"media_control",
36:"media_control",37:"media_control",38:"media_control",39:"open_app",40:"calendar_op",
41:"reminder_op",42:"reminder_op",43:"file_op",44:"print_or_scan",45:"print_or_scan",
46:"photo_edit",47:"photo_edit",48:"photo_edit",49:"photo_edit",50:"open_app",
51:"text_input_op",52:"text_to_speech_op",53:"speech_to_text_op",54:"translate",55:"translate",
56:"get_exchange_rate",57:"get_weather",58:"alarm_op",59:"alarm_op",60:"alarm_op",
61:"calculator",62:"cloud_file_op",63:"cloud_file_op",64:"cloud_file_op",65:"email_op",
66:"email_op",67:"email_op",68:"email_op",69:"video_call_op",70:"record_screen",
71:"record_screen",72:"file_op",73:"open_app",74:"open_app",75:"media_control",
76:"set_volume",77:"system_maintenance",78:"system_maintenance",79:"system_maintenance",80:"system_maintenance",
81:"system_maintenance",82:"open_app",83:"task_scheduler_op",84:"startup_program_op",85:"startup_program_op",
86:"open_app",87:"driver_op",88:"driver_op",89:"open_app",90:"dev_tool_op",
91:"dev_tool_op",92:"dev_tool_op",93:"open_app",94:"file_op",95:"git_op",
96:"git_op",97:"git_op",98:"git_op",99:"git_op",100:"git_op",
101:"git_op",102:"git_op",103:"summarize_doc",
}
AMBIGUOUS = {2, 39, 51, 61, 69, 72, 73, 74}
