# -*- coding: utf-8 -*-
"""
AERIS 100 位聲學工程師名單（摘自 AERIS_100_Acoustic_Engineers_Conversation_Record...md 第10節）。
Front Desk 的 ROUTE 步驟只能從這份清單裡選 ID，不能自己發明工程師，避免產生 AERIS 根本不認得的訂單。

v2：加上每位的核心能力簡述——v1 只有 ID+名字，實測發現 LLM 選人選不準
（例如「腔體共振」問題選到 Calibration Engineer），跟 P2 Tool Calling 踩過的坑一樣：
清單不夠、要有說明才選得準。
"""

# (id, name, 核心能力一句話)
_ENGINEERS_RAW = [
    ("001", "Chief Acoustic Architect", "全系統聲學架構規劃、trade-off"),
    ("002", "Acoustic Requirement Engineer", "把產品需求轉成可驗收規格KPI"),
    ("003", "Acoustic Design Reviewer", "設計審查、找缺口與待驗證項"),
    ("004", "Acoustic Failure Review Chief", "跨領域故障判讀、組建RCA小組"),
    ("005", "Acoustic Experiment Chief", "實驗策略、DOE、最低成本驗證計畫"),
    ("006", "Acoustic Risk Engineer", "技術風險管理、FMEA"),
    ("007", "Acoustic Statistics Engineer", "統計判讀、Cp/Cpk、ANOVA"),
    ("008", "Acoustic Evidence Engineer", "證據鏈追溯、確認結論有數據支持"),
    ("009", "Acoustic Standards Lead", "IEC/ISO/IEEE等聲學標準管理"),
    ("010", "Principal Acoustic Reviewer", "最終技術簽核、跨域審查"),
    ("011", "Loudspeaker Physics Engineer", "揚聲器電機聲模型建立"),
    ("012", "T/S Parameter Engineer", "T/S參數分析：Fs/Qts/Vas/Re/Le"),
    ("013", "Nonlinear Speaker Engineer", "大振幅非線性失真分析BL(x)/Cms(x)"),
    ("014", "Suspension Engineer", "Spider/surround懸吊系統問題"),
    ("015", "Magnetic Motor Engineer", "Voice coil/磁鐵/motor問題"),
    ("016", "Speaker Thermal Engineer", "熱壓縮、功率導致SPL下降"),
    ("017", "Diaphragm Engineer", "振膜結構、breakup、模態異常"),
    ("018", "Micro Speaker Engineer", "手機/NB小型單體設計與異常分析"),
    ("019", "Receiver Engineer", "Receiver/耳機聽筒問題"),
    ("020", "Transducer Reliability Engineer", "Driver壽命、老化、疲勞測試"),
    ("021", "Enclosure Engineer", "喇叭箱體、compliance、容積分析"),
    ("022", "Port/Vent Engineer", "低音反射孔、Helmholtz調諧"),
    ("023", "Leakage Engineer", "漏氣分析、密封路徑"),
    ("024", "Passive Radiator Engineer", "被動輻射器系統調諧"),
    ("025", "Grille/Mesh Engineer", "網布/孔洞聲阻損失分析"),
    ("026", "Acoustic Path Engineer", "出音路徑、cavity/duct共振"),
    ("027", "Speaker Array Engineer", "多喇叭陣列相位干涉"),
    ("028", "Amplifier Matching Engineer", "Amp與driver配對安全功率"),
    ("029", "Speaker Tuning Engineer", "聽感調校、target curve、EQ方向"),
    ("030", "Speaker Protection Engineer", "excursion/thermal保護策略"),
    ("031", "MEMS Microphone Engineer", "MEMS mic選型、SNR/AOP"),
    ("032", "Mic Port Engineer", "Mic port幾何、共振"),
    ("033", "Mic Mesh Engineer", "防塵防水膜聲阻分析"),
    ("034", "Microphone Array Engineer", "mic陣列geometry、spacing"),
    ("035", "Voice Pickup Engineer", "語音收音、指向性優化"),
    ("036", "Microphone Noise Engineer", "麥克風底噪、noise floor分析"),
    ("037", "Microphone Distortion Engineer", "大聲壓mic失真、飽和"),
    ("038", "Wind Noise Engineer", "戶外錄音風噪抑制"),
    ("039", "Structure-Borne Mic Engineer", "馬達/觸控震動傳導噪音"),
    ("040", "Mic Reliability Engineer", "麥克風老化、環境測試"),
    ("041", "Notebook Acoustic Engineer", "筆電speaker/mic/fan整合聲學問題"),
    ("042", "Smartphone Acoustic Engineer", "手機receiver/speaker/mic整合"),
    ("043", "Tablet Acoustic Engineer", "平板多speaker、陣列整合"),
    ("044", "Headphone/TWS Engineer", "耳機/TWS密封、ANC、驅動器"),
    ("045", "Smart Speaker Engineer", "智慧音箱遠場收音+播放整合"),
    ("046", "Conference Device Engineer", "會議機beamforming、AEC、speakerphone"),
    ("047", "TV/Monitor Acoustic Engineer", "薄型TV/顯示器喇叭腔體"),
    ("048", "Automotive Acoustic Engineer", "車艙聲學、NVH"),
    ("049", "AR/VR/Wearable Engineer", "近耳穿戴裝置聲學"),
    ("050", "Robot Acoustic Engineer", "機器人語音收音、馬達噪音"),
    ("051", "APx Engineer", "Audio Precision測試序列建立與判讀"),
    ("052", "SoundCheck Engineer", "SoundCheck測試流程與資料分析"),
    ("053", "Klippel Engineer", "Klippel LSI/LPM非線性數據分析"),
    ("054", "Anechoic Chamber Engineer", "無響室量測setup、距離角度校正"),
    ("055", "HATS Engineer", "Head/torso量測、receiver/telephony"),
    ("056", "Calibration Engineer", "麥克風/SPL校正、可追溯性"),
    ("057", "Impedance Measurement Engineer", "阻抗曲線分析找F0/leak/driver異常"),
    ("058", "Rub & Buzz Engineer", "異音偵測：buzz/rattle頻譜特徵"),
    ("059", "Production Acoustic Test Engineer", "量產EOL快速測試設計"),
    ("060", "Measurement Uncertainty Engineer", "量測誤差、不確定度分析"),
    ("061", "COMSOL Acoustic FEM Engineer", "有限元聲場模擬"),
    ("062", "BEM Acoustic Engineer", "邊界元外部輻射/散射模擬"),
    ("063", "Lumped Acoustic Model Engineer", "等效電路快速估算cavity/vent"),
    ("064", "Vibro-Acoustic Engineer", "結構振動與聲場耦合分析"),
    ("065", "Structural Modal Engineer", "外殼/振膜結構模態分析"),
    ("066", "CFD Acoustic Engineer", "流體力學噪音：port/風/渦流"),
    ("067", "Parametric Simulation Engineer", "尺寸參數掃描DOE"),
    ("068", "Acoustic Optimization Engineer", "限制條件下自動找最佳尺寸"),
    ("069", "CAD Acoustic Preparation Engineer", "CAD清理準備給模擬用"),
    ("070", "Simulation Correlation Engineer", "模擬與實測結果校正比對"),
    ("071", "EQ Engineer", "PEQ/FIR/IIR濾波器調音"),
    ("072", "Crossover Engineer", "多單體分頻設計"),
    ("073", "DRC Engineer", "動態範圍壓縮策略"),
    ("074", "Spatial Audio Engineer", "空間音訊渲染設計"),
    ("075", "Beamforming Engineer", "麥克風陣列波束成形演算法"),
    ("076", "Noise Suppression Engineer", "背景噪音抑制演算法"),
    ("077", "AEC Engineer", "回音消除演算法"),
    ("078", "ANC Engineer", "主動降噪架構設計"),
    ("079", "Automatic Tuning Engineer", "自動調音演算法優化"),
    ("080", "Acoustic ML Engineer", "音訊機器學習異常分類"),
    ("081", "Acoustic NPI Engineer", "EVT/DVT/PVT各階段聲學計畫"),
    ("082", "Acoustic Process Engineer", "膠量/裝配/壓合對聲學的製程影響"),
    ("083", "Acoustic Fixture Engineer", "EOL測試治具設計"),
    ("084", "Acoustic GR&R Engineer", "測站重複性/再現性分析"),
    ("085", "Acoustic SPC Engineer", "產線聲學數據統計製程管制"),
    ("086", "Acoustic Failure Analysis Engineer", "NG樣品根因分析、失效樹"),
    ("087", "Supplier Acoustic Quality Engineer", "供應商聲學品質審查"),
    ("088", "Acoustic Reliability Engineer", "Drop/溫濕度/壽命後聲學變化"),
    ("089", "EOL Limit Engineer", "量產測試門檻優化"),
    ("090", "Acoustic Cost Engineer", "BOM成本與聲學效能trade-off"),
    ("091", "Acoustic Data Engineer", "不同儀器資料整理成統一格式"),
    ("092", "Acoustic Knowledge Engineer", "文件建成可搜尋知識庫RAG"),
    ("093", "Acoustic Data Scientist", "大量測試資料趨勢/異常分析"),
    ("094", "Acoustic RCA Intelligence Engineer", "多來源證據自動排序根因"),
    ("095", "Acoustic DOE Copilot", "自動建立實驗設計矩陣"),
    ("096", "Acoustic Automation Engineer", "重複工程工作自動化腳本"),
    ("097", "Acoustic Technical Writer", "數據與結論整理成工程報告"),
    ("098", "Acoustic Standards Librarian", "查找正確版本標準條文"),
    ("099", "Acoustic Decision Intelligence Engineer", "多方案決策矩陣：效能/成本/風險"),
    ("100", "Principal Acoustic Integration Engineer", "整合所有專家結果成最終答案"),
]

ENGINEERS = {eid: name for eid, name, _ in _ENGINEERS_RAW}
ENGINEER_CAPABILITY = {eid: cap for eid, _, cap in _ENGINEERS_RAW}

assert len(ENGINEERS) == 100
